version: '3'

services:
  node:
    image: node:16-alpine
    container_name: app-node
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
      - type: volume
        source: node_modules
        target: /var/www/html/node_modules
    ports:
      - 3000:3000
    command: sh -c "npm run dev"
    working_dir: /var/www/html


volumes:
  node_modules:
